<script lang="ts">
  import { browser } from '$app/environment';
  import type { PageProps } from './$types';
  import { ndk } from '$lib/ndk/client';
  import ProjectCard from '$lib/components/ProjectCard.svelte';
  import { KIND_PROJECT, parseProjectEvent, type TenexProject } from '$lib/ndk/tenex';

  let { data }: PageProps = $props();

  const liveProjects = ndk.$subscribe(() => {
    if (!browser) return undefined;
    return {
      filters: [{ kinds: [KIND_PROJECT], limit: 40 }]
    };
  });

  const featuredProjects = $derived.by<TenexProject[]>(() => {
    const byAddress = new Map<string, TenexProject>();

    for (const seed of data.featuredProjects) {
      byAddress.set(seed.address, seed);
    }

    for (const event of liveProjects.events) {
      const tags = event.tags ?? [];
      const dTag = tags.find((tag) => tag[0] === 'd')?.[1];
      if (!dTag || !event.pubkey) continue;
      const address = `${KIND_PROJECT}:${event.pubkey}:${dTag}`;
      const isDeleted = tags.some((tag) => tag[0] === 'deleted');

      if (isDeleted) {
        byAddress.delete(address);
        continue;
      }

      const existing = byAddress.get(address);
      const eventCreatedAt = event.created_at ?? 0;
      if (existing && eventCreatedAt <= existing.createdAt) continue;
      const project = parseProjectEvent(event);
      if (!project) continue;
      byAddress.set(project.address, project);
    }

    return Array.from(byAddress.values())
      .sort((a, b) => b.createdAt - a.createdAt)
      .slice(0, 4);
  });
</script>

<section class="landing">
  <header class="hero">
    <h1 class="hero-title">The source code is now English.</h1>
    <p class="hero-subhead">
      We used to read code to understand how software was built. Now the real source is the
      conversation between a human and their AI agents. Open Prompt makes that conversation
      visible.
    </p>
    <div class="hero-actions">
      <a class="button" href="/projects">Browse projects →</a>
    </div>
  </header>

  <section class="essay">
    <h2 class="essay-heading">What changed</h2>
    <p>
      Open source gave us view-source for code. But code is now the compiled output — generated by
      AI from human prompts.
    </p>
    <p>
      The real source is upstream: the decisions, the taste, the corrections. "No, I meant THIS."
      "Actually, scratch that." "This feels wrong, go back."
    </p>
    <p>
      Open Prompt publishes that layer. Every project here is a TENEX project — a human building
      real software with AI agents. You're reading their mind as they build.
    </p>
  </section>

  <section class="essay">
    <h2 class="essay-heading">How it works</h2>
    <ol class="steps">
      <li>
        <span class="step-number">1</span>
        <p>A builder creates a project with AI agents on TENEX.</p>
      </li>
      <li>
        <span class="step-number">2</span>
        <p>Every conversation — every prompt, correction, decision — is a signed Nostr event.</p>
      </li>
      <li>
        <span class="step-number">3</span>
        <p>Open Prompt renders those conversations as browsable, readable content.</p>
      </li>
    </ol>
  </section>

  {#if featuredProjects.length > 0}
    <section class="featured">
      <h2 class="essay-heading">Projects</h2>
      <div class="featured-grid">
        {#each featuredProjects as project (project.address)}
          <ProjectCard {project} ownerProfile={data.profiles?.[project.pubkey]} />
        {/each}
      </div>
      <a class="featured-link" href="/projects">See all projects →</a>
    </section>
  {/if}

  <section class="essay">
    <h2 class="essay-heading">Why this matters</h2>
    <p>
      Everyone asks "will AI replace developers?" Open Prompt is the answer. Look at any project
      here. Remove the human's messages. What's left? Nothing. The prompts aren't fungible. They
      carry taste, domain knowledge, priorities — everything that makes THIS product instead of
      generic slop.
    </p>
    <p>
      The human didn't write code. The human wrote the product. The code was just the rendering.
    </p>
  </section>

  <footer class="landing-coda">
    <p>Open Prompt is itself an Open Prompt project.</p>
  </footer>
</section>

<style>
  .landing {
    display: grid;
    gap: 4rem;
    padding: 2rem 0 4rem;
  }

  .hero {
    max-width: 680px;
    margin: 0 auto;
    display: grid;
    gap: 1.5rem;
    padding: 2rem 0;
  }

  .hero-title {
    margin: 0;
    font-family: var(--font-serif);
    font-size: clamp(2.6rem, 6vw, 4.2rem);
    font-weight: 700;
    line-height: 1.02;
    letter-spacing: -0.03em;
    color: var(--text-strong);
  }

  .hero-subhead {
    margin: 0;
    font-size: 1.15rem;
    line-height: 1.55;
    color: var(--muted);
    max-width: 56ch;
  }

  .hero-actions {
    margin-top: 0.5rem;
  }

  .essay {
    max-width: 680px;
    margin: 0 auto;
    display: grid;
    gap: 1rem;
  }

  .essay-heading {
    margin: 0 0 0.5rem;
    font-family: var(--font-serif);
    font-size: 1rem;
    font-weight: 600;
    letter-spacing: 0.04em;
    text-transform: uppercase;
    color: var(--muted);
  }

  .essay p {
    margin: 0;
    font-size: 1.1rem;
    line-height: 1.65;
    color: var(--text);
  }

  .steps {
    list-style: none;
    margin: 0;
    padding: 0;
    display: grid;
    gap: 1.25rem;
  }

  .steps li {
    display: grid;
    grid-template-columns: 2rem 1fr;
    gap: 1rem;
    align-items: baseline;
  }

  .step-number {
    font-family: var(--font-serif);
    font-size: 1.4rem;
    font-weight: 700;
    color: var(--accent);
    line-height: 1;
  }

  .steps p {
    margin: 0;
    font-size: 1.1rem;
    line-height: 1.55;
    color: var(--text);
  }

  .featured {
    max-width: var(--page-width);
    margin: 0 auto;
    width: 100%;
    display: grid;
    gap: 1.5rem;
  }

  .featured .essay-heading {
    max-width: 680px;
    margin-inline: auto;
    width: 100%;
  }

  .featured-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 1rem;
  }

  .featured-link {
    justify-self: center;
    color: var(--accent);
    font-weight: 500;
    text-decoration: none;
  }

  .featured-link:hover {
    color: var(--accent-hover);
  }

  .landing-coda {
    max-width: 680px;
    margin: 1rem auto 0;
    padding-top: 2rem;
    border-top: 1px solid var(--border-light);
  }

  .landing-coda p {
    margin: 0;
    font-family: var(--font-serif);
    font-style: italic;
    color: var(--muted);
    font-size: 1.05rem;
  }
</style>
