<script lang="ts">
</script>

<article class="about">
  <header class="about-header">
    <h1>About Open Prompt</h1>
    <p class="subtitle">The source code of AI-built software.</p>
  </header>

  <section class="prose">
    <p>
      For decades, "open source" meant one thing: you could read the code. The code was the
      product, the artifact, the record of how something was built. To understand a piece of
      software, you read its source.
    </p>
    <p>
      That contract is breaking. The code is no longer where the decisions live. Software is
      increasingly generated by AI agents from human prompts — and the prompts are the real source.
      The code is the rendering.
    </p>
    <p>
      Open Prompt publishes the upstream layer. Every conversation that built a product — every
      ask, every correction, every "no, do it this way" — is the actual source code of the age
      we're in. View source still matters. The thing being viewed has just moved.
    </p>
  </section>

  <section class="prose">
    <h2>What you'll find here</h2>
    <div class="definition-list">
      <div class="definition-row">
        <span>Projects</span>
        <p>Real TENEX projects where humans build software with AI agents.</p>
      </div>
      <div class="definition-row">
        <span>Conversations</span>
        <p>The actual exchanges — prompts, corrections, decisions — that shaped the product.</p>
      </div>
      <div class="definition-row">
        <span>Builders</span>
        <p>The humans behind the work, identified by their Nostr keys.</p>
      </div>
    </div>
  </section>

  <section class="prose">
    <h2>The technology</h2>
    <p>
      Everything on Open Prompt is built on Nostr. Conversations are signed events, portable
      across relays, censorship-resistant, and not tied to any one platform. No accounts to
      create — identities are cryptographic. Data lives on relays, not in our database.
    </p>
  </section>

  <section class="prose">
    <h2>The meta</h2>
    <p>
      Open Prompt is built using TENEX. The conversations that built this product are themselves
      browsable on Open Prompt. The medium is the message.
    </p>
  </section>
</article>

<style>
  .about {
    max-width: 680px;
    margin: 0 auto;
    display: grid;
    gap: 3rem;
    padding: 2rem 0 4rem;
  }

  .about-header {
    display: grid;
    gap: 0.75rem;
    padding-bottom: 1rem;
    border-bottom: 1px solid var(--border-light);
  }

  .about-header h1 {
    margin: 0;
    font-family: var(--font-serif);
    font-size: clamp(2.2rem, 5vw, 3rem);
    font-weight: 700;
    letter-spacing: -0.02em;
    line-height: 1.05;
    color: var(--text-strong);
  }

  .subtitle {
    margin: 0;
    font-family: var(--font-serif);
    font-style: italic;
    font-size: 1.25rem;
    color: var(--muted);
  }

  .prose {
    display: grid;
    gap: 1rem;
  }

  .prose h2 {
    margin: 0 0 0.25rem;
    font-family: var(--font-serif);
    font-size: 1rem;
    font-weight: 600;
    letter-spacing: 0.04em;
    text-transform: uppercase;
    color: var(--muted);
  }

  .prose p {
    margin: 0;
    font-size: 1.1rem;
    line-height: 1.65;
    color: var(--text);
  }
</style>
